// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diabetic.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231022200456_AddSeederForAssigningRecipeToMeal")]
    partial class AddSeederForAssigningRecipeToMeal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Diabetic.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warzywa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Owoce"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Produkty zbożowe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Orzechy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nabiał"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mięso, ryby, jaja"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Słodycze"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sosy"
                        });
                });

            modelBuilder.Entity("Diabetic.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Day 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Day 2"
                        });
                });

            modelBuilder.Entity("Diabetic.Models.Day_Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BreakfastRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<int?>("DinnerRecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("LunchRecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("SnackRecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("SupperRecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Day_Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreakfastRecipeId = 6,
                            DayId = 1,
                            DinnerRecipeId = 2,
                            LunchRecipeId = 4,
                            SupperRecipeId = 5
                        },
                        new
                        {
                            Id = 2,
                            BreakfastRecipeId = 8,
                            DayId = 2,
                            DinnerRecipeId = 7,
                            LunchRecipeId = 9,
                            SupperRecipeId = 10
                        });
                });

            modelBuilder.Entity("Diabetic.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Snack"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Supper"
                        });
                });

            modelBuilder.Entity("Diabetic.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("GI")
                        .HasColumnType("int");

                    b.Property<int?>("GramsPerPortion")
                        .HasColumnType("int");

                    b.Property<int>("KcalPer100g")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            GI = 20,
                            KcalPer100g = 33,
                            Name = "marchew"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            GI = 39,
                            KcalPer100g = 33,
                            Name = "marchewka gotowana"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            GI = 51,
                            KcalPer100g = 86,
                            Name = "groszek zielony"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            GI = 52,
                            KcalPer100g = 80,
                            Name = "słodka kukurydza"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            GI = 56,
                            KcalPer100g = 1000,
                            Name = "ziemniak gotowany"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            GI = 40,
                            KcalPer100g = 76,
                            Name = "bób (surowy)"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            GI = 53,
                            KcalPer100g = 46,
                            Name = "Śliwka czerwona"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            GI = 45,
                            GramsPerPortion = 50,
                            KcalPer100g = 330,
                            Name = "Płatki orkiszowe"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            GI = 69,
                            KcalPer100g = 79,
                            Name = "ziemniak pieczony"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            GI = 20,
                            KcalPer100g = 26,
                            Name = "bakłażan"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            GI = 30,
                            KcalPer100g = 42,
                            Name = "burak"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 33,
                            Name = "cebula"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 17,
                            Name = "cukinia"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            GI = 33,
                            KcalPer100g = 315,
                            Name = "fasola biała ugotowana"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 27,
                            Name = "kalafior"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 33,
                            Name = "kapusta biała"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 31,
                            Name = "kapusta czerwona"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 43,
                            Name = "kapusta włoska"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 14,
                            Name = "ogórek"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 32,
                            Name = "papryka czerwona"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 22,
                            Name = "papryka zielona"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            GI = 10,
                            KcalPer100g = 21,
                            Name = "pieczarki"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            GI = 19,
                            KcalPer100g = 19,
                            Name = "pomidor"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 29,
                            Name = "por"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            GI = 72,
                            KcalPer100g = 33,
                            Name = "rzepa"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 18,
                            Name = "rzodkiewka"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            GI = 10,
                            KcalPer100g = 14,
                            Name = "sałata"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            GI = 10,
                            KcalPer100g = 16,
                            Name = "sałata lodowa"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            GI = 35,
                            KcalPer100g = 30,
                            Name = "seler korzeń"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 17,
                            Name = "seler naciowy"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            GI = 26,
                            KcalPer100g = 341,
                            Name = "soczewica gotowana"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 22,
                            Name = "szpinak"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 31,
                            Name = "brokuł"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 18,
                            Name = "kapusta kiszona"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            GI = 52,
                            KcalPer100g = 49,
                            Name = "pietruszka"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 33,
                            Name = "fasolka szparagowa"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            GI = 35,
                            KcalPer100g = 213,
                            Name = "suszone pomidory"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            GI = 35,
                            KcalPer100g = 23,
                            Name = "pomidory z puszki"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            GI = 15,
                            KcalPer100g = 23,
                            Name = "ogórek konserwowy"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            GI = 59,
                            KcalPer100g = 55,
                            Name = "ananas"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            GI = 15,
                            KcalPer100g = 46,
                            Name = "agrest"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            GI = 72,
                            KcalPer100g = 36,
                            Name = "arbuz"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            GI = 10,
                            KcalPer100g = 169,
                            Name = "awokado"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            GI = 52,
                            KcalPer100g = 97,
                            Name = "banan"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            GI = 30,
                            KcalPer100g = 50,
                            Name = "brzoskwinia"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            GI = 22,
                            KcalPer100g = 63,
                            Name = "czereśnie"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            GI = 25,
                            KcalPer100g = 40,
                            Name = "grejpfrut"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            GI = 38,
                            KcalPer100g = 58,
                            Name = "gruszka"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 2,
                            GI = 37,
                            KcalPer100g = 50,
                            Name = "jabłko"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            GI = 53,
                            KcalPer100g = 60,
                            Name = "kiwi"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            GI = 25,
                            KcalPer100g = 43,
                            Name = "maliny"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 2,
                            GI = 30,
                            KcalPer100g = 45,
                            Name = "mandarynki"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            GI = 51,
                            KcalPer100g = 59,
                            Name = "mango"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 2,
                            GI = 65,
                            KcalPer100g = 24,
                            Name = "melon"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 2,
                            GI = 57,
                            KcalPer100g = 50,
                            Name = "morele"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 2,
                            GI = 35,
                            KcalPer100g = 50,
                            Name = "nektarynki"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 2,
                            GI = 42,
                            KcalPer100g = 47,
                            Name = "pomarańcza"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 2,
                            GI = 15,
                            KcalPer100g = 35,
                            Name = "porzeczka czarna"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 2,
                            GI = 39,
                            KcalPer100g = 49,
                            Name = "śliwki"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 2,
                            GI = 40,
                            KcalPer100g = 33,
                            Name = "truskawki"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            GI = 46,
                            KcalPer100g = 71,
                            Name = "winogron"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 2,
                            GI = 22,
                            KcalPer100g = 49,
                            Name = "wiśnie"
                        },
                        new
                        {
                            Id = 137,
                            CategoryId = 2,
                            GI = 55,
                            KcalPer100g = 57,
                            Name = "borówki"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 3,
                            GI = 54,
                            GramsPerPortion = 50,
                            KcalPer100g = 334,
                            Name = "kasza gryczana"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 3,
                            GI = 48,
                            GramsPerPortion = 50,
                            KcalPer100g = 213,
                            Name = "chleb razowy na zakwasie"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 3,
                            GI = 55,
                            KcalPer100g = 289,
                            Name = "pełnoziarniste spaghetti"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 3,
                            GI = 53,
                            KcalPer100g = 334,
                            Name = "kosmosa ryżowa, quinoa"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            GI = 55,
                            KcalPer100g = 376,
                            Name = "płatki owsiane"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 3,
                            GI = 61,
                            KcalPer100g = 365,
                            Name = "makaron ryżowy"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 3,
                            GI = 50,
                            KcalPer100g = 335,
                            Name = "ryż brązowy"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 3,
                            GI = 54,
                            KcalPer100g = 379,
                            Name = "biszkopt"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 3,
                            GI = 70,
                            KcalPer100g = 258,
                            Name = "chleb pszenny"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 3,
                            GI = 58,
                            KcalPer100g = 229,
                            Name = "chleb żytni pełnoziarnisty"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 3,
                            GI = 50,
                            KcalPer100g = 227,
                            Name = "chleb żytni razowy"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 3,
                            GI = 70,
                            KcalPer100g = 300,
                            Name = "kajzerka"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 3,
                            GI = 71,
                            KcalPer100g = 348,
                            Name = "kasza jaglana ugotowana"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 3,
                            GI = 70,
                            KcalPer100g = 335,
                            Name = "kasza jęczmienna perłowa gotowana"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 3,
                            GI = 25,
                            KcalPer100g = 343,
                            Name = "kasza jęczmienna pęczak"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 3,
                            GI = 55,
                            KcalPer100g = 352,
                            Name = "kasza manna"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 3,
                            GI = 55,
                            KcalPer100g = 340,
                            Name = "makaron dwujajeczny"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 3,
                            GI = 81,
                            KcalPer100g = 381,
                            Name = "płatki kukurydziane"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 3,
                            GI = 49,
                            GramsPerPortion = 40,
                            KcalPer100g = 244,
                            Name = "chleb orkiszowy"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 3,
                            GI = 57,
                            KcalPer100g = 357,
                            Name = "muslie"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 4,
                            GI = 15,
                            KcalPer100g = 604,
                            Name = "migdały"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 4,
                            GI = 14,
                            KcalPer100g = 610,
                            Name = "orzechy arachidowe "
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 4,
                            GI = 15,
                            KcalPer100g = 666,
                            Name = "orzechy laskowe"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 4,
                            GI = 15,
                            KcalPer100g = 621,
                            Name = "pistacje"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 4,
                            GI = 15,
                            KcalPer100g = 666,
                            Name = "orzechy włoskie"
                        },
                        new
                        {
                            Id = 138,
                            CategoryId = 4,
                            GI = 15,
                            KcalPer100g = 630,
                            Name = "mieszanka orzechów"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 5,
                            GI = 36,
                            KcalPer100g = 60,
                            Name = "jogurt naturalny 2%"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 5,
                            GI = 27,
                            KcalPer100g = 49,
                            Name = "jogurt naturalny 0%"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 5,
                            GI = 32,
                            KcalPer100g = 51,
                            Name = "kefir 2%"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 5,
                            GI = 32,
                            KcalPer100g = 39,
                            Name = "mleko 0,5%"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 5,
                            GI = 55,
                            KcalPer100g = 61,
                            Name = "mleko 3,2%"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 5,
                            GI = 61,
                            KcalPer100g = 326,
                            Name = "mleko słodzone zagęszczone"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 150,
                            Name = "ser kozi miękki"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 254,
                            Name = "ser mozarella"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 5,
                            GI = 30,
                            KcalPer100g = 68,
                            Name = "ser twarogowy chudy"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 260,
                            Name = "ser feta"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 332,
                            Name = "brie pełnotłusty"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 293,
                            Name = "ser camembert"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 383,
                            Name = "ementaler"
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 354,
                            Name = "salami"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 134,
                            Name = "śmietana 12%"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 186,
                            Name = "śmietana 18%"
                        },
                        new
                        {
                            Id = 136,
                            CategoryId = 5,
                            GI = 0,
                            KcalPer100g = 140,
                            Name = "jajko"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 217,
                            Name = "kaczka"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 172,
                            Name = "kiełbasa domowa"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 213,
                            Name = "kiełbasa żywiecka"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 92,
                            Name = "krewetki gotowane"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 115,
                            Name = "królik"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 98,
                            Name = "kurczak"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 228,
                            Name = "łosoś z rusztu"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 165,
                            Name = "polędwica sopocka"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 346,
                            Name = "salami (kiełbasa)"
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 123,
                            Name = "szynka z kurczaka"
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 106,
                            Name = "szynka wołowa"
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 126,
                            Name = "szynka z indyka"
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 6,
                            GI = 25,
                            KcalPer100g = 336,
                            Name = "śledź w oleju"
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 129,
                            Name = "tuńczyk z rusztu"
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 252,
                            Name = "tuńczyk w zalewie"
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 268,
                            Name = "kotlet schabowy"
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 112,
                            Name = "polędwica wołowa"
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 172,
                            Name = "kiełbasa domowa"
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 6,
                            GI = 0,
                            KcalPer100g = 84,
                            Name = "indyk"
                        },
                        new
                        {
                            Id = 133,
                            CategoryId = 6,
                            GI = 0,
                            GramsPerPortion = 45,
                            KcalPer100g = 480,
                            Name = "kabanos"
                        },
                        new
                        {
                            Id = 135,
                            CategoryId = 6,
                            GI = 0,
                            GramsPerPortion = 90,
                            KcalPer100g = 161,
                            Name = "podudzie z kurczaka"
                        },
                        new
                        {
                            Id = 139,
                            CategoryId = 6,
                            GI = 0,
                            GramsPerPortion = 200,
                            KcalPer100g = 98,
                            Name = "pierś z kurczaka"
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 7,
                            GI = 57,
                            KcalPer100g = 335,
                            Name = "ciasteczka owsiane"
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 7,
                            GI = 22,
                            KcalPer100g = 645,
                            Name = "czekolada gorzka"
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 7,
                            GI = 43,
                            KcalPer100g = 530,
                            Name = "czekolada mleczna"
                        },
                        new
                        {
                            Id = 126,
                            CategoryId = 7,
                            GI = 44,
                            KcalPer100g = 564,
                            Name = "czekolada biała"
                        },
                        new
                        {
                            Id = 127,
                            CategoryId = 7,
                            GI = 57,
                            KcalPer100g = 428,
                            Name = "herbatniki "
                        },
                        new
                        {
                            Id = 128,
                            CategoryId = 7,
                            GI = 65,
                            KcalPer100g = 542,
                            Name = "baton mars"
                        },
                        new
                        {
                            Id = 129,
                            CategoryId = 7,
                            GI = 44,
                            KcalPer100g = 493,
                            Name = "twix"
                        },
                        new
                        {
                            Id = 130,
                            CategoryId = 7,
                            GI = 60,
                            KcalPer100g = 300,
                            Name = "lody"
                        },
                        new
                        {
                            Id = 131,
                            CategoryId = 7,
                            GI = 78,
                            KcalPer100g = 306,
                            Name = "żelki"
                        },
                        new
                        {
                            Id = 132,
                            CategoryId = 8,
                            GI = 0,
                            KcalPer100g = 679,
                            Name = "majonez"
                        },
                        new
                        {
                            Id = 134,
                            CategoryId = 8,
                            GI = 25,
                            GramsPerPortion = 25,
                            KcalPer100g = 327,
                            Name = "hummus"
                        });
                });

            modelBuilder.Entity("Diabetic.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Pieczone podudzia z kurczaka z quinąą i surówką"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jajka, kabanos"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Owoce, jogurt, orzechy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Owsianka z owocami i orzechami"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sałatka Orzo"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kanapka z szynką i warzywami"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pieczona pierś z kurczaka z suszonymi pomidorami, fasolką szparagową i ryżem brązowym"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kanapki z warzywami"
                        });
                });

            modelBuilder.Entity("Diabetic.Models.Recipe_Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Recipe_Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Amount = 180,
                            ProductId = 135,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50,
                            ProductId = 66,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100,
                            ProductId = 19,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 120,
                            ProductId = 136,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 45,
                            ProductId = 133,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 11,
                            Amount = 100,
                            ProductId = 137,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 12,
                            Amount = 150,
                            ProductId = 88,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 13,
                            Amount = 30,
                            ProductId = 138,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 14,
                            Amount = 200,
                            ProductId = 36,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 15,
                            Amount = 50,
                            ProductId = 69,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 16,
                            Amount = 200,
                            ProductId = 139,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 17,
                            Amount = 20,
                            ProductId = 37,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 18,
                            Amount = 100,
                            ProductId = 91,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 19,
                            Amount = 50,
                            ProductId = 67,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 20,
                            Amount = 200,
                            ProductId = 137,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 21,
                            Amount = 20,
                            ProductId = 138,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 30,
                            Amount = 50,
                            ProductId = 113,
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 22,
                            Amount = 10,
                            ProductId = 132,
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 23,
                            Amount = 40,
                            ProductId = 19,
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 24,
                            Amount = 25,
                            ProductId = 134,
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 25,
                            Amount = 40,
                            ProductId = 81,
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 26,
                            Amount = 40,
                            ProductId = 81,
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 27,
                            Amount = 50,
                            ProductId = 113,
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 28,
                            Amount = 25,
                            ProductId = 134,
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 29,
                            Amount = 40,
                            ProductId = 19,
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 6,
                            Amount = 80,
                            ProductId = 81,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 50,
                            ProductId = 23,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 8,
                            Amount = 25,
                            ProductId = 134,
                            RecipeId = 6
                        });
                });

            modelBuilder.Entity("MealRecipe", b =>
                {
                    b.Property<int>("MealsId")
                        .HasColumnType("int");

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.HasKey("MealsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("MealRecipe");

                    b.HasData(
                        new
                        {
                            MealsId = 1,
                            RecipesId = 5
                        });
                });

            modelBuilder.Entity("Diabetic.Models.Product", b =>
                {
                    b.HasOne("Diabetic.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Diabetic.Models.Recipe_Ingredients", b =>
                {
                    b.HasOne("Diabetic.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diabetic.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealRecipe", b =>
                {
                    b.HasOne("Diabetic.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diabetic.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diabetic.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
